# Nixpacks Configuration for VM Visa Frontend
# This configures Nixpacks to build a static SPA

[variables]
NODE_ENV = "production"
NIXPACKS_SPA_OUTPUT_DIR = "dist/spa"

[phases.build]
cmd = "npm run build:client"

[phases.start] 
cmd = "npx serve -s dist/spa -l 3000"

[providers.node]
version = "18"